/**
 * UUIDv7 — time-ordered identifiers.
 *
 * MySQL's InnoDB clusters every table on its primary key, so random UUIDv4
 * primary keys scatter inserts across the whole B-tree and fragment it. UUIDv7
 * puts a millisecond timestamp in the leading 48 bits, so new rows land at the
 * end of the index the way an AUTO_INCREMENT would — while still being
 * generated by the application, which matters because MySQL has no RETURNING
 * clause and we would otherwise need a round-trip to learn the id we just made.
 *
 * Layout (RFC 9562):
 *   48 bits  unix time in milliseconds
 *    4 bits  version (7)
 *   12 bits  random
 *    2 bits  variant (10)
 *   62 bits  random
 */

const HEX: string[] = Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, '0'));

/**
 * @param now  milliseconds since epoch — injectable so tests are deterministic
 * @param rand 10 random bytes — injectable for the same reason
 */
export function uuidv7(
  now: number = Date.now(),
  rand: Uint8Array = crypto.getRandomValues(new Uint8Array(10)),
): string {
  if (!Number.isInteger(now) || now < 0) {
    throw new RangeError(`uuidv7 timestamp must be a non-negative integer, received ${now}.`);
  }
  if (rand.length < 10) {
    throw new RangeError(`uuidv7 needs 10 random bytes, received ${rand.length}.`);
  }

  const b = new Uint8Array(16);

  // 48-bit big-endian timestamp. Split above/below 2^32 because bitwise
  // operators in JS are 32-bit and would silently truncate.
  const hi = Math.floor(now / 0x1_0000_0000);
  const lo = now >>> 0;
  b[0] = (hi >>> 8) & 0xff;
  b[1] = hi & 0xff;
  b[2] = (lo >>> 24) & 0xff;
  b[3] = (lo >>> 16) & 0xff;
  b[4] = (lo >>> 8) & 0xff;
  b[5] = lo & 0xff;

  b[6] = 0x70 | (rand[0]! & 0x0f); // version 7
  b[7] = rand[1]!;
  b[8] = 0x80 | (rand[2]! & 0x3f); // variant 10
  for (let i = 0; i < 7; i++) b[9 + i] = rand[3 + i]!;

  const h = (i: number) => HEX[b[i]!]!;
  return (
    h(0) + h(1) + h(2) + h(3) + '-' +
    h(4) + h(5) + '-' +
    h(6) + h(7) + '-' +
    h(8) + h(9) + '-' +
    h(10) + h(11) + h(12) + h(13) + h(14) + h(15)
  );
}

/** Milliseconds since epoch encoded in a v7 id. Useful for debugging and sorting. */
export function uuidv7Time(id: string): number {
  const hex = id.replace(/-/g, '').slice(0, 12);
  if (hex.length !== 12) throw new RangeError(`"${id}" is not a UUID.`);
  return Number.parseInt(hex, 16);
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isUuid(value: string): boolean {
  return UUID_RE.test(value);
}
